#Uses 

name: TrendMicro Cloud One RASP Custom Rule Deployment in a CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TP_API_KEY: ${{ secrets.TP_API_KEY }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip' #cache needs requirements.txt use pip freeze > requirements.txt from your activated venv
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Deploy Custom RASP rule from static file
      run: |
        python trend-rasp-custom-rule-ci.py #requires refactoring to specify multiple files/iterations
