name: Splunk SPL Testing

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - tests/*.log
      - tests/*.txt
      - buildspec.txt
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#when running commit prior to a push you setup the cli parameters that should trigger a detection
env:
  #COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
  SPLUNK_USER: ${{ secrets.SPLUNK_USER }}
  SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
  SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
  
permissions:
      contents: read    # This is required for actions/checkout

jobs:
  splRuleTests:
    # The type of runner that the job will run on
    #runs-on: Ubuntu-latest
    runs-on: [self-hosted, splunk] #based on logical combination of labels
    #environment: production
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      #run SPL checks based on buildspec.txt 
      #depends on splunk already being installed and configured
      - name: Set Root Privs
        run: |
          export RUNNER_ALLOW_RUNASROOT=1  
      - name: Switch to Root
        run: |
          echo '$SUDO_PASSWORD' | sudo -S bash    
      - name: Check Splunk Status
        run: |
          echo '$SUDO_PASSWORD' | sudo -S /opt/splunk/bin/splunk status
          #find . -type f -print0 | xargs -0 dos2unix
      - name: Run SPL Validation
        run: |
          echo '$SUDO_PASSWORD' | sudo -S chmod +x ./spl-integration-test.sh
          dos2unix ./spl-integration-test.sh
          dos2unix ./buildspec.txt
          ./spl-integration-test.sh
